"use client";

import { useCallback, useState, useSyncExternalStore } from "react";
import { Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { cn } from "@/lib/utils";
import { formatCurrency } from "@/lib/format";
import type { SummaryDrivers, SummaryHolding } from "@/lib/daily-summary";

const SEEN_KEY = "houndstooth:summary-seen";

export type DailySummary = {
  date: string;
  model: string | null;
  drivers: SummaryDrivers;
};

/** SSR-safe read of the last-seen summary date from localStorage. */
function useSeenDate(): string | null {
  const subscribe = useCallback((cb: () => void) => {
    window.addEventListener("storage", cb);
    return () => window.removeEventListener("storage", cb);
  }, []);
  return useSyncExternalStore(
    subscribe,
    () => localStorage.getItem(SEEN_KEY),
    () => null,
  );
}

export function DailySummaryBanner({ summary }: { summary: DailySummary | null }) {
  const seenDate = useSeenDate();
  const [open, setOpen] = useState(false);
  const [dismissed, setDismissed] = useState(false);

  if (!summary) return null;

  const persistedSeen = seenDate === summary.date;
  const showBanner = !dismissed && !persistedSeen;

  function markSeen() {
    setDismissed(true);
    try {
      localStorage.setItem(SEEN_KEY, summary!.date);
    } catch {
      // ignore storage failures
    }
  }

  return (
    <>
      {showBanner && (
        <div className="flex items-center gap-3 rounded-xl border border-primary/30 bg-primary/10 px-4 py-3">
          <Sparkles className="size-5 shrink-0 text-primary" />
          <div className="min-w-0 flex-1">
            <div className="text-sm font-medium">Your daily summary is ready</div>
            <div className="truncate text-sm text-muted-foreground">
              {summary.drivers.headline}
            </div>
          </div>
          <Button size="sm" onClick={() => setOpen(true)}>
            View
          </Button>
          <button
            aria-label="Dismiss"
            onClick={markSeen}
            className="text-muted-foreground hover:text-foreground"
          >
            <X className="size-4" />
          </button>
        </div>
      )}

      <Dialog
        open={open}
        onOpenChange={(v) => {
          setOpen(v);
          if (!v) markSeen();
        }}
      >
        <DialogContent className="max-h-[85vh] gap-0 overflow-hidden p-0 sm:max-w-2xl">
          <div className="max-h-[85vh] space-y-5 overflow-y-auto px-6 py-5">
            <SummaryContent summary={summary} />
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

function SummaryContent({ summary }: { summary: DailySummary }) {
  const d = summary.drivers;
  const tickered = d.holdings.filter((h) => h.ticker);

  return (
    <>
      <DialogHeader className="pr-8">
        <div className="text-xs font-medium uppercase tracking-wide text-primary">
          Daily summary ·{" "}
          {new Date(`${summary.date}T00:00:00`).toLocaleDateString("en-US", {
            weekday: "long",
            month: "short",
            day: "numeric",
          })}
        </div>
        <DialogTitle className="text-xl leading-snug">{d.headline}</DialogTitle>
      </DialogHeader>

      {/* Tiles */}
      <div className="grid grid-cols-2 gap-3">
        <Tile label="Net Worth" value={d.tiles.net_worth} />
        <Tile label="Investments" value={d.tiles.investments} />
      </div>

      <Section title="Macro market">{d.macro_summary}</Section>
      <Section title="Portfolio drivers">{d.portfolio_summary}</Section>
      <Section title="What to watch">{d.watch}</Section>

      {/* Holdings table */}
      {tickered.length > 0 && (
        <div>
          <h3 className="mb-2 text-sm font-semibold">Holdings</h3>
          <div className="rounded-xl border border-border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Holding</TableHead>
                  <TableHead className="text-right">Value</TableHead>
                  <TableHead className="text-right">Change</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {tickered.map((h) => (
                  <HoldingRow key={`${h.ticker}-${h.name}`} h={h} />
                ))}
              </TableBody>
            </Table>
          </div>
        </div>
      )}

      <p className="pt-2 text-xs text-muted-foreground">
        Informational market commentary — not financial advice.
        {summary.model ? ` Generated by ${summary.model}.` : ""}
      </p>
    </>
  );
}

function HoldingRow({ h }: { h: SummaryHolding }) {
  const flag = h.isMover ? (h.direction === "up" ? "🚀" : "🔻") : null;
  return (
    <TableRow>
      <TableCell>
        <div className="flex items-center gap-1.5 font-medium">
          {flag && <span aria-hidden>{flag}</span>}
          {h.ticker}
        </div>
        <div className="text-xs text-muted-foreground">{h.name}</div>
        {h.isMover && h.reason && (
          <div className="mt-1 max-w-md text-xs text-muted-foreground">
            {h.reason}
          </div>
        )}
      </TableCell>
      <TableCell className="text-right align-top font-medium tabular-nums">
        {formatCurrency(h.value)}
      </TableCell>
      <TableCell className="text-right align-top tabular-nums">
        {h.changePct == null ? (
          <span className="text-muted-foreground">—</span>
        ) : (
          <span
            className={cn(
              h.direction === "up" && "text-gain",
              h.direction === "down" && "text-loss",
            )}
          >
            {h.changePct > 0 ? "+" : ""}
            {h.changePct.toFixed(2)}%
          </span>
        )}
      </TableCell>
    </TableRow>
  );
}

function Tile({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-xl border border-border p-4">
      <div className="text-sm text-muted-foreground">{label}</div>
      <div className="mt-1 text-xl font-semibold tabular-nums">
        {formatCurrency(value)}
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="mb-1 text-sm font-semibold">{title}</h3>
      <p className="text-sm leading-relaxed text-muted-foreground">{children}</p>
    </div>
  );
}
